[metadata]
name = cncv
version = 0.1.0
author = Ali Siahkoohi
author_email = alisk@ucf.edu
description = Conditional Neural Control Variates for variance reduction in Bayesian inference
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/luqigroup/cncv
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
install_requires =
    matplotlib
    numpy
    scipy
    tqdm
    torch
    projorg
    pytest
packages = find:
python_requires = >=3.9

[options.packages.find]
exclude =
    tests*
    scripts*
    docs*
    data*
    plots*
