#!/bin/bash
# Helmholtz FWI amortized CNCV pipeline.
# Trains the CNF then the CNCV on the joint (z, y) Helmholtz data generated by
# scripts/generate_helmholtz_joint.py, reusing the train_darcy_kl.py
# infrastructure: the data file's `u_kl` key is the KL coefficients of the
# velocity field and `y_obs` is the [real|imag] Helmholtz observations.

set -e
cd "$(dirname "$0")/.."
# Activate your Python environment (with cncv installed) before running.

LOG_DIR=logs/rebuttal_higher_d
mkdir -p $LOG_DIR

DATA=data/helmholtz/helmholtz_K10_N131072_grid32.npz
CNF_DIR=data/helmholtz/checkpoints_cnf_131k
CNCV_DIR=data/helmholtz/checkpoints_cncv_131k

mkdir -p data/helmholtz

echo "==============================================="
echo "Helmholtz CNF training (N=131072, matches Darcy v2)"
echo "==============================================="
date

python scripts/train_darcy_kl.py --phase cnf --gpu 0 \
    --data_path $DATA \
    --cnf_hidden 128 --cnf_flow_layers 12 --cnf_depth 6 --cnf_mlp_layers 3 \
    --cnf_epochs 80 --cnf_batchsize 1024 \
    --cnf_lr 0.001 --cnf_lr_final 0.00001 \
    --cnf_num_train 120000 --cnf_num_val 11072 \
    --cnf_weight_decay 0.0001 --cnf_grad_clip 10.0 \
    --cnf_ckpt_dir $CNF_DIR \
    --checkpoint_freq 10 \
    2>&1 | tee $LOG_DIR/helmholtz_cnf_131k.log

echo "==============================================="
echo "Helmholtz CNCV training (N=131072, matches Darcy v2)"
echo "==============================================="
date

python scripts/train_darcy_kl.py --phase cncv --gpu 0 \
    --data_path $DATA \
    --cnf_checkpoint $CNF_DIR/cnf_best.pth \
    --cncv_ensemble 16 --cncv_hidden 128 --cncv_depth 3 --cncv_mlp_layers 5 \
    --cncv_epochs 150 --cncv_batchsize 1024 \
    --cncv_lr 0.0001 --cncv_lr_final 0.00001 \
    --cncv_num_train 120000 --cncv_num_val 11072 \
    --cncv_ckpt_dir $CNCV_DIR \
    --checkpoint_freq 20 \
    2>&1 | tee $LOG_DIR/helmholtz_cncv_131k.log

echo "==============================================="
echo "Helmholtz pipeline done at $(date)"
echo "==============================================="
